name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up CMake
      run: |
        sudo apt-get -y install cmake
        echo "PATH=$PATH:/usr/bin/cmake" >> $GITHUB_ENV
        cmake --version

    - name: Install Asio
      run: |
        sudo apt-get install -yq libasio-dev \
        cmake

    - name: Build project
      run: |
        cd json-server
        mkdir build
        cd build
        cmake ../
        make
        
    - name: Start local server
      run: |
        cd json-server
        cd build
        ./json-server &
        sleep 10

    - name: Run tests
      run: |
        cd json-server
        cd build
        cd tests
        ./tests
