name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v2
      with:
        cmake-version: '3.21'

    - name: Build project
      run: |
        mkdir build
        cd build/json-server
        cmake ../..
        make

    - name: Run tests
      run: |
        cd build/json-server
        ctest
