name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

   - name: Set up CMake
      uses: crazy-max/setup-cmake@v1
      with:
        cmake-version: '3.21'
        binary-dir: '${{ github.workspace }}/cmake-bin'

    - name: Build project
      run: |
        mkdir build
        cd build/json-server
        cmake ../..
        make

    - name: Run tests
      run: |
        cd build/json-server
        ctest
