name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      run: |
        sudo apt-get -y install cmake
        echo "::add-path::/usr/bin/cmake"
        cmake --version

    - name: Build project
      run: |
        mkdir build
        cd build/json-server
        cmake ../..
        make

    - name: Run tests
      run: |
        cd build/json-server
        ctest
